on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GHC
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8'
          cabal-version: '3.12.1.0'
          enable-stack: true
          stack-version: '3.1.1'
      - name: Run Tests
        run: make test
